# Paths for the Google Drive's folders - used in merge_files (to download, upload and move files to archive)
from tweet_classifier import TaskName

# Deltas folders paths - see urls in GDrive WebUI
DELTA_US_ISRAEL_SENTIMENT_TWEET_FOLDER_ID = "1UAR9E72axE6PGqc56IRnA9iv0Ij7nil7"
DELTA_US_HOUTHIS_TWEET_FOLDER_ID = "1fclsTRug5c9j-AUYXCodM3Iz8UEDS4Io"
DELTA_UK_FOLDER_ID = "1lmvdANqy7US-sDo85ggp5cHLTiQNnEIV"
DELTA_GERMANY_FOLDER_ID = "1wBy8evQz2JNs6M6GRgvA4kbptZnFQzkw"
DELTA_FRANCE_FOLDER_ID = "18Ojp8Fu8tYdoKIWGUgbDqH9eUNeo57-l"

DELTA_FOLDER_ID_DICT = {"us": {
    TaskName.IsraelSentimentTweet: DELTA_US_ISRAEL_SENTIMENT_TWEET_FOLDER_ID,
    TaskName.HouthisTweet: DELTA_US_HOUTHIS_TWEET_FOLDER_ID}
}

ALL_DATA_US_ISRAEL_SENTIMENT_TWEET_FOLDER_ID = "1-yz46x737WQsvT-CQGcPe5m5l2Cyz518"
ALL_DATA_US_HOUTHIS_TWEET_FOLDER_ID = "1SPyNxm3zQZWUBwCFoyfS7cKLAD3LFuwF"
ALL_DATA_US_UNRWA_FOLDER_ID = "1CKNdBivpMtBPvnb0LkXcNJufGWXqh8s4"
ALL_DATA_UK_FOLDER_ID = "1oatV9iYQEM6jNu9J5GNT5I6u1X-yJ6-b"
ALL_DATA_FRANCE_FOLDER_ID = "1vMGkGbdWTTMrt3OVGdVgAj4M5OPF3A96"
ALL_DATA_GERMANY_FOLDER_ID = "1nW1EAK79SPgQvDOtawYP6f6deftHXcIE"

ALL_DATA_FOLDER_ID_DICT = {"us": {
    TaskName.IsraelSentimentTweet: ALL_DATA_US_ISRAEL_SENTIMENT_TWEET_FOLDER_ID,
    TaskName.HouthisTweet: ALL_DATA_US_HOUTHIS_TWEET_FOLDER_ID,
    TaskName.Unrwa: ALL_DATA_US_UNRWA_FOLDER_ID}
}

# after verification folders paths
AFTER_VER_US_ISRAEL_SENTIMENT_TWEET_FOLDER_ID = "1XxZ8r6O1jiMwRBApuNO6cj8U7Kwr2pnr"
AFTER_VER_US_HOUTHIS_TWEET_FOLDER_ID = "1U_ZRcloHL6WYvftDM94OA7Z6Sa-zeeS_"
AFTER_VER_US_UNRWA_TWEET_FOLDER_ID = "1rVIOGqLoeby4WaUG8OGYeTwEgxdvAuaF"
AFTER_VER_UK_FOLDER_ID = "1tB8GuWh5as8P-y58FnkjF18deg1nd84K"
AFTER_VER_GERMANY_FOLDER_ID = "1Mleh2hGYidmyutZn2ACk203V0nNQ4eBv"
AFTER_VER_FRANCE_FOLDER_ID = "1FU8L0PKte_bPxN-Fy_Ot0TfRQO-scYd-"

AFTER_VER_FOLDER_ID_DICT = {"us": {
    TaskName.IsraelSentimentTweet: AFTER_VER_US_ISRAEL_SENTIMENT_TWEET_FOLDER_ID,
    TaskName.HouthisTweet: AFTER_VER_US_HOUTHIS_TWEET_FOLDER_ID,
    TaskName.Unrwa: AFTER_VER_US_UNRWA_TWEET_FOLDER_ID
    }
}

# archive folders paths
ARCHIVE_US_ISRAEL_SENTIMENT_TWEET_FOLDER_ID = "1rCewnO5sXgnTZXKzecH9QfxAshWGFtdf"
ARCHIVE_US_HOUTHIS_TWEET_FOLDER_ID = "1VkN9b-xIywdXSnAjeKCPk8q2GLVAMDCd"
ARCHIVE_US_UNRWA_TWEET_FOLDER_ID = "1ih4t84eTBaoxVIxzRX-9wINT9jVFfPZF"
ARCHIVE_UK_FOLDER_ID = "14dYAan-Ag09ZQr611dSz73jiywa6Az0w"
ARCHIVE_GERMANY_FOLDER_ID = "17ZO4i_9u5H4mEfCI2LqirHqiCX-2IiAo"
ARCHIVE_FRANCE_FOLDER_ID = "1lL5TRvMhfH8UCQDx9GoK6DKflXOPjYOt"

ARCHIVE_FOLDER_ID_DICT = {"us": {
    TaskName.IsraelSentimentTweet: ARCHIVE_US_ISRAEL_SENTIMENT_TWEET_FOLDER_ID,
    TaskName.HouthisTweet: ARCHIVE_US_HOUTHIS_TWEET_FOLDER_ID, 
    TaskName.Unrwa: ARCHIVE_US_UNRWA_TWEET_FOLDER_ID}
}

FOR_VER_US_ISRAEL_SENTIMENT_TWEET_FOLDER_ID = "1q3d95tpm323lVMh87xWCNmHWvNcsCcBG"
FOR_VER_US_HOUTHIS_TWEET_FOLDER_ID = "1-KKWbx4rGQl3sD21jk3iP3ukswszLwhN"
FOR_VER_US_UNRWA_TWEET_FOLDER_ID = "1BYT4DrQQh1OMLlPs0IJCYYMlHKfkzbzv"
FOR_VER_UK_FOLDER_ID = "1MQ5mFDcnmQG7fetJpYruyE1BOTFdVOvQ"
FOR_VER_GERMANY_FOLDER_ID = "1-c-YXghAsWx0-dFjh1UGqifbxy1Y9hQa"
FOR_VER_FRANCE_FOLDER_ID = "1JQz_82qn0RtYNcGKUhXuodiKyxjIRBdp"

FOR_VER_FOLDER_ID_DICT = {"us": {
    TaskName.IsraelSentimentTweet: FOR_VER_US_ISRAEL_SENTIMENT_TWEET_FOLDER_ID,
    TaskName.HouthisTweet: FOR_VER_US_HOUTHIS_TWEET_FOLDER_ID,
    TaskName.Unrwa: FOR_VER_US_UNRWA_TWEET_FOLDER_ID}
}

REDUCE_EMBEDDINGS_US_ISRAEL_SENTIMENT_TWEET_FOLDER_ID = "1io1ZKL38kKSgFEBJEqXZ4D5XbS_46lvF"
REDUCE_EMBEDDINGS_US_HOUTHIS_TWEET_FOLDER_ID = "1D1oh4a4UtLG7kKEGlOn0RI4OU6FRnOxH"

REDUCE_EMBEDDINGS_FOLDER_ID_DICT = {"us": {
    TaskName.IsraelSentimentTweet:
        REDUCE_EMBEDDINGS_US_ISRAEL_SENTIMENT_TWEET_FOLDER_ID,
    TaskName.HouthisTweet: REDUCE_EMBEDDINGS_US_HOUTHIS_TWEET_FOLDER_ID}
}


def get_folder_id(country, task_name, folder_id_dict):
    country_dict = folder_id_dict.get(country, 0)
    assert country_dict != 0, "not supported country"

    id_folder = country_dict.get(task_name, 0)
    assert id_folder != 0, "not supported task"

    return id_folder
